/* eslint-disable max-lines, max-lines-per-function */
/**
 * Per-block output field schemas for Frink Flows.
 *
 * These schemas describe what each block type puts in `node_runs.node_output.outputs`
 * when it completes. They are used by:
 * - The flow editor "Available Variables" UI panel (renderer)
 * - The `frink-flows` Claude skill (references generated by
 *   `scripts/build-skill-content.ts` and shipped to `~/.frink/skills/frink-flows/`)
 *
 * **Authoritative runtime shapes** — what handlers actually write into `outputs` — live in
 * `src/main/lib/flows/dispatch/`. Update those handlers and this file together.
 */
/**
 * Declares one output field produced by a custom node.
 * Defined here (shared) so both the Electron main process (discovery, cloud DTO)
 * and the renderer (AvailableVariables hook) can import the same type.
 */
export type ManifestOutputField = {
  type: 'string' | 'number' | 'boolean' | 'object' | 'array';
  description?: string;
  /** Sub-fields for array-of-objects. Omit for arrays of primitives. */
  items?: Record<string, ManifestOutputField>;
};
/**
 * Declares what JSON fields a `run_command` node will output to stdout.
 * Stored in the node's `config.expectedOutputs`. Same shape as custom node manifest outputs.
 *
 * When declared, these fields appear as chips in the Available Variables panel and are
 * validated by the template variable checker. `exitCode` is always present in addition.
 *
 * Example config:
 * ```json
 * {
 *   "timestamp": { "type": "string", "description": "ISO timestamp of execution" },
 *   "message": { "type": "string", "description": "Status message" }
 * }
 * ```
 */
export type RunCommandExpectedOutputs = Record<string, ManifestOutputField>;
export type OutputFieldSchema = {
  key: string;
  /** JSON-level type of the value */
  type: 'string' | 'number' | 'boolean' | 'object' | 'array' | 'unknown';
  description: string;
  /** True if this field is always present; false if it only appears in some cases */
  guaranteed: boolean;
};
export type TriggerFieldSchema = {
  key: string;
  type: 'string' | 'number' | 'boolean' | 'object' | 'array' | 'unknown';
  description: string;
  /** Which trigger types produce this field (omit to mean "all triggers") */
  triggers?: string[];
  /**
   * True for an open-ended object whose sub-fields can't be validated at design
   * time (e.g. `payload` = the raw provider webhook body). The editor renders
   * `{{trigger.<key>.*}}` deep paths as "dynamic" (resolves at runtime) rather
   * than confident-valid, since field names are provider-specific.
   */
  openEnded?: boolean;
};
/**
 * Output fields each block type writes to `outputs` when it completes.
 * Accessible in templates as `{{previous.<key>}}`.
 *
 * Notes:
 * - `run_command` / custom nodes: if stdout is valid JSON, its fields are spread
 *   into outputs alongside `exitCode`. If not JSON, `_rawStdout` is populated instead.
 * - `condition`: passes through all upstream `outputs` fields plus `result`.
 * - `fan_out`: the body node sees a synthetic `outputs` with `currentItem` etc.
 *   The node after fan_out sees aggregated `results`.
 * - `approval`: no outputs (flow is paused, not completed).
 * - Trigger blocks: no previous outputs (use `{{trigger.*}}` instead).
 */
export const OUTPUT_SCHEMAS: Record<string, OutputFieldSchema[]> = {
  run_command: [
    {
      key: 'exitCode',
      type: 'number',
      description: 'Process exit code (0 = success)',
      guaranteed: true,
    },
    {
      key: '_rawStdout',
      type: 'string',
      description: 'Raw stdout truncated to 4KB — only present when stdout is not valid JSON',
      guaranteed: false,
    },
  ],
  start_task: [
    {
      key: 'chatId',
      type: 'string',
      description:
        'Chat session ID created for this flow run — downstream agent blocks continue this chat',
      guaranteed: true,
    },
    {
      key: 'subChatId',
      type: 'string',
      description:
        'Default sub-chat ID for this flow session — downstream chat_reply targets this tab',
      guaranteed: true,
    },
    {
      key: 'projectId',
      type: 'string',
      description: 'Project the Start Task is bound to',
      guaranteed: true,
    },
    {
      key: 'worktreePath',
      type: 'string',
      description: 'Absolute path to the git worktree (empty string when startInWorktree is false)',
      guaranteed: true,
    },
    {
      key: 'branch',
      type: 'string',
      description: 'Git branch checked out in the worktree',
      guaranteed: false,
    },
    {
      key: 'baseBranch',
      type: 'string',
      description: 'Base branch (parent of the working branch)',
      guaranteed: false,
    },
    {
      key: 'configured',
      type: 'boolean',
      description: 'True when the worktree was provisioned; false for no-worktree runs',
      guaranteed: true,
    },
    {
      key: 'mergedBranches',
      type: 'array',
      description:
        'Dependency branches merged into the converging worktree (sc-612). Absent on single-branch runs; ' +
        'the field may be omitted when not applicable. Available via {{previous.mergedBranches}}.',
      guaranteed: false,
    },
    {
      key: 'mergeConflict',
      type: 'boolean',
      description:
        'True when a converging merge conflict was detected (node status will be awaiting_input). ' +
        'Absent on clean merges.',
      guaranteed: false,
    },
    {
      key: 'conflictingBranch',
      type: 'string',
      description:
        'The dependency branch that caused the merge conflict (present when mergeConflict is true).',
      guaranteed: false,
    },
    {
      key: 'conflictedFiles',
      type: 'array',
      description: 'File paths with merge conflicts (present when mergeConflict is true).',
      guaranteed: false,
    },
  ],

  /**
   * Note: If the flow has a `briefing` set in Flow Settings (graph.settings.briefing), it is
   * delivered once per flow session as a system prompt to every agent — it is
   * NOT prepended to this block's `instructions` or repeated in the message. Rendered once per run
   * against {{trigger.*}}. Lets a root agent set shared PRD/spec context without touching each node.
   */
  agent: [
    {
      key: 'summary',
      type: 'string',
      description: 'Short summary the agent reported on completion',
      guaranteed: false,
    },
    {
      key: 'details',
      type: 'string',
      description: 'Detailed output the agent reported on completion',
      guaranteed: false,
    },
    {
      key: 'chatId',
      type: 'string',
      description: 'Chat session ID — used by downstream agent and chat_reply blocks',
      guaranteed: true,
    },
    {
      key: 'worktreePath',
      type: 'string',
      description: 'Absolute path to the git worktree used by this agent',
      guaranteed: false,
    },
    {
      key: 'branch',
      type: 'string',
      description: 'Git branch the agent worked on',
      guaranteed: false,
    },
    {
      key: 'baseBranch',
      type: 'string',
      description: 'Base branch',
      guaranteed: false,
    },
    {
      key: 'spawnedTaskId',
      type: 'string',
      description: 'Task ID — only present when fireAndForget is true',
      guaranteed: false,
    },
    {
      key: 'fireAndForget',
      type: 'boolean',
      description: 'True when agent was launched in async fire-and-forget mode',
      guaranteed: false,
    },
    {
      key: 'taskStatus',
      type: 'string',
      description:
        'Task status when the node ended in a non-standard state (e.g. needs_attention when agent did not signal). Use {{previous.taskStatus}} to branch on this.',
      guaranteed: false,
    },
    {
      key: 'verification',
      type: 'object',
      description:
        "Structured verification result from the agent's frink_task_signal call — only present when the agent explicitly includes a verification object. Use dot notation: {{previous.verification.passed}}",
      guaranteed: false,
    },
  ],

  http_request: [
    {
      key: 'status',
      type: 'number',
      description: 'HTTP response status code (e.g. 200)',
      guaranteed: true,
    },
    {
      key: 'statusText',
      type: 'string',
      description: 'HTTP response status text (e.g. "OK")',
      guaranteed: true,
    },
    {
      key: 'body',
      type: 'string',
      description: 'Response body as a string (truncated at 256KB)',
      guaranteed: true,
    },
    {
      key: 'headers',
      type: 'object',
      description:
        'Response headers as key/value pairs. Use dot notation: {{previous.headers.content-type}}',
      guaranteed: true,
    },
    {
      key: 'truncated',
      type: 'boolean',
      description: 'True if the response body was truncated due to size limit',
      guaranteed: true,
    },
  ],

  /**
   * Iteration-time outputs: visible inside the fan_out body chain nodes.
   * At completion time, the node after fan_out sees `fan_out_completed` fields instead.
   */
  fan_out: [
    {
      key: 'currentItem',
      type: 'unknown',
      description:
        'Current array element for this iteration — shape depends on the upstream array. Use dot notation for object fields: {{previous.currentItem.title}}',
      guaranteed: true,
    },
    {
      key: 'currentIndex',
      type: 'number',
      description: 'Zero-based index of the current iteration',
      guaranteed: true,
    },
    {
      key: 'totalCount',
      type: 'number',
      description: 'Total number of items being iterated',
      guaranteed: true,
    },
    {
      key: 'arrayField',
      type: 'string',
      description: 'Name of the field from the upstream output that is being iterated',
      guaranteed: true,
    },
  ],

  /**
   * Completion-time outputs: visible on the node that follows the fan_out container.
   * The engine writes `_fanOutState: "completed"` to distinguish these from iteration-time outputs.
   *
   * Note: `results` serialises to JSON in templates. For >25 lanes the ~50 KB per-placeholder
   * cap in template-utils.ts is likely to be exceeded, silently leaving `{{previous.results}}`
   * as a literal string. Use a `run_command` API fetch instead of template expansion for large
   * batches. See the `frink-flows` skill (`SKILL.md`).
   */
  fan_out_completed: [
    {
      key: 'results',
      type: 'array',
      description:
        "One record per item, keyed by branch-root node id. Each value is that branch tail's `outputs` record. Use `{{previous.results.0.<branchRootNodeId>.summary}}` for scalar access. Large arrays (>25 items) can exceed the 50 KB template cap — prefer API fetch.",
      guaranteed: true,
    },
    {
      key: 'totalCount',
      type: 'number',
      description:
        'Total number of items processed across all parallel or sequential iterations (including skipped lanes). In parallel mode this equals the fan_out item count, not the per-wave lane cap.',
      guaranteed: true,
    },
    {
      key: '_fanOutState',
      type: 'string',
      description:
        'Internal marker set to "completed" when all lanes have finished. Used by the UI to detect fan-out completion outputs vs iteration outputs.',
      guaranteed: true,
    },
  ],

  condition: [
    {
      key: 'result',
      type: 'string',
      description: '"true" on the true branch, "stop" on the false branch',
      guaranteed: true,
    },
  ],

  end: [],

  chat_reply: [
    {
      key: 'chatId',
      type: 'string',
      description: 'Chat session ID the message was posted into',
      guaranteed: true,
    },
    {
      key: 'subChatId',
      type: 'string',
      description: 'Sub-chat tab the assistant message was appended to',
      guaranteed: true,
    },
    {
      key: 'delivered',
      type: 'boolean',
      description: 'Whether the message was successfully delivered',
      guaranteed: true,
    },
    {
      key: 'message',
      type: 'string',
      description: 'The rendered text message or interactive artifact title',
      guaranteed: true,
    },
    {
      key: 'contentType',
      type: 'string',
      description: 'Either text or html_artifact',
      guaranteed: true,
    },
    {
      key: 'artifactId',
      type: 'string',
      description: 'Stable artifact delivery ID (HTML artifact replies only)',
      guaranteed: false,
    },
    {
      key: 'title',
      type: 'string',
      description: 'Rendered preview title (HTML artifact replies only)',
      guaranteed: false,
    },
  ],
};

/**
 * Fields available on `{{trigger.*}}` based on which trigger type fired the flow.
 * These come from `flow_runs.trigger_context`, not from block outputs.
 */
export const TRIGGER_SCHEMAS: Record<string, TriggerFieldSchema[]> = {
  post_task_trigger: [
    { key: 'taskId', type: 'string', description: 'UUID of the completed task' },
    { key: 'taskTitle', type: 'string', description: 'Title of the completed task' },
    { key: 'taskStatus', type: 'string', description: 'Final status of the task' },
    {
      key: 'source',
      type: 'string',
      description: 'How the task was created (e.g. manual, flow, slack)',
    },
    { key: 'projectId', type: 'string', description: 'UUID of the project the task belonged to' },
    { key: 'result', type: 'string', description: 'Result summary from the task signal' },
    { key: 'branch', type: 'string', description: 'Git branch the task ran on' },
    { key: 'baseBranch', type: 'string', description: 'Base branch the task branched from' },
    { key: 'worktreePath', type: 'string', description: 'Absolute path to the task worktree' },
    { key: 'chatId', type: 'string', description: 'Chat session ID of the triggering task' },
    { key: 'projectPath', type: 'string', description: 'Main project directory path' },
  ],
  schedule_trigger: [
    {
      key: 'scheduledAt',
      type: 'string',
      description: 'ISO timestamp when this run was scheduled',
    },
  ],
  // Fields the LOCAL flow webhook path actually produces (buildWebhookTriggerContext
  // in src/main/lib/flows/webhook-trigger.ts) plus the aliaser additions. Friendly
  // per-provider sub-fields (e.g. {{trigger.story.title}}) are layered on top at the
  // editor + render via TRIGGER_FIELD_ALIASES; `payload` is the raw escape hatch.
  webhook_trigger: [
    {
      key: 'source',
      type: 'string',
      description: 'Integration provider (shortcut, gmail, slack, etc.)',
    },
    {
      key: 'event',
      type: 'string',
      description: 'Webhook event type (alias of eventType)',
    },
    {
      key: 'eventType',
      type: 'string',
      description: 'Webhook event type',
    },
    {
      key: 'triggeredBy',
      type: 'object',
      description: 'Actor who caused the event — use dot paths, e.g. triggeredBy.externalUserId',
    },
    {
      key: 'timestamp',
      type: 'string',
      description: 'ISO time when the trigger fired',
    },
    {
      key: 'sourceAccountId',
      type: 'string',
      description: 'Connected integration id',
    },
    {
      key: 'integrationId',
      type: 'string',
      description: 'Connected integration id (same as sourceAccountId)',
    },
    {
      key: 'deliveryId',
      type: 'string',
      description: "This delivery's unique id — the provider's own, or a payload fingerprint",
    },
    {
      key: 'payload',
      type: 'object',
      openEnded: true,
      description:
        'Raw provider webhook body. Field names are provider-specific — prefer the friendly fields above (e.g. {{trigger.story.title}}); use payload.* only as an escape hatch.',
    },
  ],
  manual_trigger: [
    {
      key: 'label',
      type: 'string',
      description:
        'Per-run display label shown in the Frink Monitor run list. Set by the CEO agent in triggerContext. Falls back to "Run N" when absent.',
    },
    {
      key: 'customInstructions',
      type: 'string',
      description:
        'Run-specific agent instructions editable until dispatch. Merged into the agent system prompt at run time. Max 10 000 characters.',
    },
    {
      key: 'baseBranch',
      type: 'string',
      description:
        'For root batch stages, set triggerContext.baseBranch to the starting branch. For dependent stages, the server resolves and overwrites it from completed dependencies at dispatch; do not precompute their base branch.',
    },
    {
      key: 'baseBranches',
      type: 'array',
      description:
        'Base branches from all completed dependencies, ordered most-recently-completed first (converging DAG deps). Client uses baseBranches[0] as primary base and merges the rest. Provided alongside baseBranch whenever dependency branches resolve, including a single branch. baseBranch equals baseBranches[0].',
    },
    {
      key: 'mergeStrategy',
      type: 'string',
      description:
        'Merge strategy hint for converging DAG branches; currently always "most-recent". Client-side agent uses baseBranches[0] as primary worktree base.',
    },
  ],
};

/**
 * Trigger types where triggerContext keys are user-supplied and open-ended.
 * `checkTriggerPath` skips unknown-field warnings for these types.
 *
 * `manual_trigger` accepts arbitrary user-defined keys via `define_stages` /
 * `frink_flows_run` `triggerContext` (e.g. ticketId, workstreamId, storyId).
 * The `buildFlowTemplateVariables` runtime spreads the full `flowTriggerContext`
 * onto `trigger.*` with no filtering, so any key is valid at runtime.
 */
export const TRIGGER_ALLOWS_ARBITRARY_KEYS: ReadonlySet<string> = new Set(['manual_trigger']);

/**
 * Fallback output schema for custom nodes that don't declare their outputs in manifest.json.
 * Follows the same shape as run_command: exitCode + optional _rawStdout when stdout isn't JSON.
 * When a custom node declares `outputs` in its manifest, those fields are used instead.
 */
export const CUSTOM_NODE_FALLBACK_OUTPUT_SCHEMA: OutputFieldSchema[] = OUTPUT_SCHEMAS.run_command;

/** Converts manifest-declared output fields into `OutputFieldSchema[]` — shared by the
 * renderer and `frink_flows_patch` so both resolve a manifest's outputs identically. */
export function manifestOutputsToSchema(
  outputs: Record<string, ManifestOutputField> | undefined,
): OutputFieldSchema[] {
  if (!outputs) return [];
  return Object.entries(outputs).map(([key, field]) => ({
    key,
    type: field.type as OutputFieldSchema['type'],
    description: field.description ?? key,
    guaranteed: true,
  }));
}

/** Converts `expectedOutputs` into `OutputFieldSchema[]`, prepending the always-present
 * `exitCode` unless the caller already declared one. */
export function resolveRunCommandOutputSchema(
  expectedOutputs: RunCommandExpectedOutputs,
): OutputFieldSchema[] {
  const exitCodeField = OUTPUT_SCHEMAS.run_command?.find((f) => f.key === 'exitCode');
  const declared = manifestOutputsToSchema(expectedOutputs);
  if (exitCodeField && !declared.some((f) => f.key === 'exitCode')) {
    return [exitCodeField, ...declared];
  }
  return declared;
}

/** Scalar `{{loop.*}}` fields for every node inside a fan_out body chain (per-item
 * fields like `{{loop.currentItem.*}}` are resolved separately). */
export const LOOP_CONTEXT_SCHEMA: OutputFieldSchema[] = [
  {
    key: 'currentIndex',
    type: 'number',
    description: 'Zero-based index of the current iteration (0 = first item)',
    guaranteed: true,
  },
  {
    key: 'totalCount',
    type: 'number',
    description: 'Total number of items being iterated',
    guaranteed: true,
  },
];
