import type { PluginPackageContents, PluginSkill } from '../plugins';
import { builtinRuntimeSupport, withStagedDelivery } from '../plugin-runtime-support';
import type { VendorPluginPin } from '../vendor-plugin-pins';
import canva from './canva.json';
import huggingface from './huggingface.json';
import clickup from './clickup.json';
import neon from './neon.json';
import notion from './notion.json';
import posthog from './posthog.json';
import sentry from './sentry.json';
import supabase from './supabase.json';
import vercel from './vercel.json';

type VendorInventory = {
  pin: VendorPluginPin;
  pluginId: string;
  /** Package-relative display metadata; runtime readers resolve their own installed paths. */
  skills: PluginSkill[];
  commands: string[];
};

interface VendorInventories {
  readonly [pluginId: string]: VendorInventory;
}

/** Generated by scripts/plugin-catalog/generate.ts from the exact source revisions. */
export const VENDOR_INVENTORIES: VendorInventories = {
  canva,
  // SAFETY: same shape, wider string literals in the generated file.
  huggingface: huggingface as VendorInventory,
  clickup,
  neon,
  notion,
  posthog,
  sentry,
  // SAFETY: same shape, wider string literals in the generated file.
  supabase: supabase as VendorInventory,
  // SAFETY: same shape, wider string literals in the generated file.
  vercel: vercel as VendorInventory,
};

export function catalogRuntimeSupport(
  pluginId: string,
  contents: PluginPackageContents,
  vendorPluginsEnabled?: boolean,
) {
  const matrix = builtinRuntimeSupport(contents, vendorPluginsEnabled);
  const inventory = VENDOR_INVENTORIES[pluginId];
  return inventory ? withStagedDelivery(matrix, inventory) : matrix;
}
