import { Button, Input } from '@benord-labs/frink-primitives';
import { useId, useState } from 'react';
import { trpc } from '@/lib/trpc';

type Props = { integrationId: string; webhookId: string };

/** Import a subscription created outside Frink with the secret generated by ClickUp. */
export function ClickupManualSetup({
  integrationId,
  webhookId,
  vendorRef,
}: Props & { vendorRef?: string | null }) {
  const [vendorWebhookId, setVendorWebhookId] = useState(
    vendorRef?.replace(/^manual:clickup:/, '') ?? '',
  );
  const [secret, setSecret] = useState('');
  const id = useId();
  const utils = trpc.useUtils();
  const save = trpc.triggerSetup.importClickupWebhook.useMutation({
    onSuccess: () => {
      setSecret('');
      void utils.integrations.listWebhookEndpoints.invalidate({ integrationId });
      void utils.integrations.list.invalidate();
    },
  });
  return (
    <form
      className="space-y-3"
      onSubmit={(event) => {
        event.preventDefault();
        save.mutate({
          integrationId,
          webhookId,
          vendorWebhookId: vendorWebhookId.trim(),
          secret: secret.trim(),
        });
      }}
    >
      <p className="text-xs text-muted-fg">
        Create a ClickUp webhook using this address, then save its ID and the signing secret ClickUp
        returned.
      </p>
      <label htmlFor={`${id}-webhook`} className="block space-y-1 text-xs">
        <span>ClickUp webhook ID</span>
        <Input
          id={`${id}-webhook`}
          value={vendorWebhookId}
          onChange={(event) => setVendorWebhookId(event.target.value)}
          readOnly={Boolean(vendorRef)}
        />
      </label>
      <label htmlFor={`${id}-secret`} className="block space-y-1 text-xs">
        <span>ClickUp signing secret</span>
        <Input
          id={`${id}-secret`}
          type="password"
          autoComplete="off"
          value={secret}
          onChange={(event) => setSecret(event.target.value)}
        />
      </label>
      {save.error ? (
        <p role="alert" className="text-xs text-destructive">
          {save.error.message}
        </p>
      ) : null}
      <Button
        type="submit"
        size="sm"
        variant="secondary"
        loading={save.isPending}
        disabled={!vendorWebhookId.trim() || !secret.trim()}
      >
        {vendorRef ? 'Update signing secret' : 'Save ClickUp webhook'}
      </Button>
    </form>
  );
}
